# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/msm8953-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter albus ali sanders,$(TARGET_DEVICE)),)

endif
